version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=shoeguard
      - POSTGRES_USER=shoeguard
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./volumes/psql_db/:/var/lib/postgresql/data

  test_db:
    image: postgres
    ports:
      - "5433:5432"
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=shoeguard
      - POSTGRES_USER=shoeguard
      - POSTGRES_HOST_AUTH_METHOD=trust
    tmpfs:
      - /var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "fsync=off"

  was:
    build: .
    restart: "unless-stopped"
    expose:
      - 8000
    environment:
      - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
      - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
    env_file:
      - .env
    volumes:
      - ./volumes/staticfiles/:/app/shoeguard/static

  ws:
    build: ./nginx
    restart: "unless-stopped"
    depends_on:
      - was
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./volumes/staticfiles/:/home/app/shoeguard/static
