# Generated by Django 3.2.6 on 2021-08-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
