# Generated by Django 3.2.6 on 2021-09-23 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210923_1327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_alter_report_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='parent_child_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.parentchildpair'),
        ),
    ]
