# Generated by Django 3.2.6 on 2021-09-23 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='partner',
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentchildpair',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_pair', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentchildpair',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_pair', to=settings.AUTH_USER_MODEL),
        ),
    ]
