# Generated by Django 3.2.6 on 2021-09-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210923_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentChildPair',
        ),
    ]
