# Generated by Django 3.2.6 on 2021-09-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='code',
            field=models.IntegerField(),
        ),
    ]
