# Generated by Django 3.2.6 on 2021-09-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_history', '0002_auto_20210923_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationhistory',
            name='parent_child_pair',
        ),
    ]
