# Generated by Django 3.2.6 on 2021-09-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_history', '0003_remove_locationhistory_parent_child_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationhistory',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
