name: Test

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Setup DB for Test
        run: docker-compose up -d test_db
      # Setup Environments

      - name: Cache Dependencies
        id: cache-dependency
        uses: actions/cache@v2
        with:
          path: .venv
          key: virtualenv_${{ runner.os }}_${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: poetry install
        if: steps.cache-dependency.cache-hit != 'true'
      # Install Dependencies

      - name: Run Tests
        run: poetry run pytest . --migrations

      - name: Teardown DB
        run: docker-compose down
